#!/usr/bin/python3

import os
import easygui
import shutil
import datetime
import sys

title = 'Mode Creator'

msg = 'Please enter mode name'
field_names = ['Mode Name']
mode_name = easygui.multenterbox(msg, title, field_names)[0].replace(' ', '_')

mode_filepath = os.path.join(os.getcwd(), mode_name) + '.sh'
if os.path.isfile(mode_filepath):
    sys.exit('Mode already exists...')

msg = 'Please enter paths'
field_names = ['Path', 'Path', 'Path', 'Path', 'Path']
paths = easygui.multenterbox(msg, title, field_names)

exec_paths = list()
for path in list(filter(None, paths)):
    print('Adding: "%s"' % path)
    if os.path.exists(path) or shutil.which(path) is not None:
        exec_paths.append('%s\n' % path)
    else:
        print('\tError: "%s" doesn\'t exist...' % path)

with open(mode_filepath, 'a') as f:
    f.writelines('#!/bin/bash\n\n')
    f.writelines('# MeaLabs Mode Creator\n')
    f.writelines('# Autogenerated %s\n\n' % datetime.datetime.now())
    f.writelines(exec_paths)
